ViewModels/Forum/ForumIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForumApp.ViewModels.Forum
{
    public class ForumIndexModel
    {
        public IEnumerable<ForumListingModel> ListOfForums { get; set; }
        //public string Message { get; set; }


    }
}

ViewModels/Forum/ForumListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForumApp.ViewModels.Forum
{
    public class ForumListingModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }

    }
}

ViewModels/Forum/ForumTopicModel.cs
using ForumApp.ViewModels.Posts;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForumApp.ViewModels.Forum
{
    public class ForumTopicModel
    {
        public IEnumerable<PostListingModel> Posts { get; set; }
        public ForumListingModel Forum { get; set; }

    }
}

Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Forum.Data.Interface;
using Forum.Data.Model;
using ForumApp.ViewModels.Forum;
using ForumApp.ViewModels.Posts;
using Microsoft.AspNetCore.Mvc;

namespace ForumApp.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _PostService;

        public ForumController(IForum forumservice, IPost post)
        {
            this._forumService = forumservice;
            this._PostService = post;
        }
        public IActionResult Index()
        {
            var forum = _forumService.GetAllForums();

            var forumViewModel = forum
                .Select(x => new ForumListingModel
                {
                    Id = x.Id,
                    Title = x.Title,
                    Description = x.Description
                });

            var model = new ForumIndexModel
            {
                ListOfForums = forumViewModel  
            };
          
            return View(model);
        }

        public IActionResult Topic(int id)
        {
            var forum = _forumService.GetForumById(id);

            var posts = forum.Posts;

           // var posts = _PostService.GetPostsByForum(id);

            var PostListings = posts.Select(post => new PostListingModel
            {

                Id = post.Id,
                AuthorId = post.User.Id,
                AuthorRating = post.User.Rating,
                Title = post.Title,
                DatePosted = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = BuildForumListing(post)
            });

            var model = new ForumTopicModel
            {
                Posts = PostListings,
                Forum = BuildForumListing(forum)
            };

            return View(model);
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;

            return BuildForumListing(forum);
        }

        private ForumListingModel BuildForumListing(Forumm forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Title = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }
    }
}

Views/Forum/Index.cshtml
@model ForumIndexModel

@{
    ViewBag.Title = "Forums";
}

<h1>Forums</h1>

<table class="table table-hover" id="forumIndexTable">
    <thead>
        <tr>
            <th>Title</th>
          <th> Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var forum in @Model.ListOfForums)
        {
        <tr class="assetRow">

            <td class="">
                <a asp-controller="Forum" asp-action="Topic" asp-route-Id="@forum.Id">
                    @forum.Title
                </a>
            </td>

            <td class="">
                @forum.Description
            </td>
        </tr>
        }
    </tbody>

</table>

Views/Forum/Topic.cshtml
@model ForumTopicModel

@{ 
    ViewBag.Title = "Topics";
}

<h1> Welcome to the @Model.Forum.Title Forum !</h1>

@if (Model.Posts.Any())
{
    <table class="table table-bordered table-hover">

        <tbody>
            @foreach (var post in Model.Posts)
            {

            <tr>
                <td>

                    <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">

                        <span> @post.Title </span>
                    </a>
                  
                </td>

                <td>

                    @post.AuthorName
                </td>

                <td>

                    @post.DatePosted

                </td>

                <td>

                     @post.RepliesCount
                </td>
            </tr>

            }
        </tbody>
    </table>
}
else 
{
    <div class="no-post">
        <h3>
            It looks like there are no @Model.Forum.Title posts yet. <br />
            Why not 
            <a asp-controller="Post" asp-action="Create" asp-route-id="@Model.Forum.Id"> 
            
                <span> Create One ? </span>
            </a>
        </h3>
    </div>
}